# Generated by Django 4.0.5 on 2022-06-10 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordercomplete', models.CharField(max_length=256)),
                ('paymentcomplete', models.CharField(max_length=256)),
                ('cancel', models.CharField(max_length=256)),
                ('deliverystart', models.CharField(max_length=256)),
                ('deliverycomplete', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productsave', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'productorders',
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('ordertime', models.CharField(max_length=256)),
                ('allprice', models.CharField(max_length=256)),
                ('sale', models.CharField(max_length=256)),
                ('finalprice', models.CharField(max_length=256)),
                ('validity', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'userorders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('price', models.CharField(max_length=256)),
                ('stock', models.CharField(max_length=256)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
