# Generated by Django 4.0.5 on 2022-06-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='cancel',
            new_name='statusname',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='deliverycomplete',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='deliverystart',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='ordercomplete',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='paymentcomplete',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default=True, max_length=256),
        ),
    ]
